include:
  - file: .vue.gitlab-ci.yml
    ref: stable
    project: "oops/cicd"

variables:
  SENTRY_URL: ""
  SENTRY_PROJECT: ""
  SENTRY_AUTH_TOKEN: ""
  SENTRY_ORG: ""

  ALLURE_ENABLED: "false"
  ALLURE_PROJECT_ID: ""

  PRODUCTION_INGRESS_URL: "https://frontend-default-project"
  # PRODUCTION_INGRESS_ADDITIONAL_URL_0: ""
  # PRODUCTION_INGRESS_ADDITIONAL_URL_1: ""
  # ...
  # PRODUCTION_INGRESS_ADDITIONAL_URL_N: ""

  STAGING_INGRESS_URL: "https://$CI_PROJECT_NAME-staging.$KUBE_INGRESS_BASE_DOMAIN"
  # STAGING_INGRESS_ADDITIONAL_URL_0: ""
  # ...
  # STAGING_INGRESS_ADDITIONAL_URL_N: ""

  REVIEW_INGRESS_URL: "https://$CI_PROJECT_ID-$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN"
  # REVIEW_INGRESS_ADDITIONAL_URL_0: ""
  # ...
  # REVIEW_INGRESS_ADDITIONAL_URL_N: ""
